name = "sam-dev-blog"
compatibility_date = "2024-09-29"

[env.production]
name = "sam-dev-blog"

# Pages 配置
pages_build_output_dir = "dist"

# 環境變數 (如果需要的話)
# [env.production.vars]
SITE_URL = "https://sam-dev.space"
